### ISSUE TITLE
Consider adopting cweagans/bg-sync?

### ISSUE THREAD

**Issue by cweagans** [phase2/outrigger-unison#1]
We've got essentially the same approach, but my container doesn't have any dependencies on the host. If there's something that I can change on my end to make it an easier/more appealing transition, I'd be glad to work with you guys on it.

https://github.com/cweagans/docker-bg-sync

**Comment by grayside** [comment]
Hi @cweagans, thanks for reaching out! I gave docker-bg-sync a quick review and I'm not sure your current model would help us.

Our current approach in development is to use one container for assembling dependencies and running other build operations which are then surfaced back to the local machine. The apache container then pulls that code to serve it up operationally. With a model such as that, it looks to me like this approach of getting code into the sync container would have the same performance problems as not using unison at all.

To clarify our approach beyond what the outrigger-unison README describes, there is also http://docs.outrigger.sh/project-setup/filesystem-sync/ which lays out how our CLI handles the unison heavy-lifting, and uses an externally created named volume to surface the synchronized code inside the containers.

As a secondary point, we are trying to avoid dependency on volumes_from, since it is unsupported in docker-compose v3+.

**Comment by cweagans** [comment]
Talked about this at badcamp. Sounds like we've got sufficiently different approaches that there's not much overlap here.
